spring:
  application:
    name: web-demo

server:
  port: 8080

security:
  basic:
    enabled: false

logging:
  level: debug


---

spring:
  profiles: dev

server:
  port: 9001

---

spring:
  profiles: production

server:
  port: 9002
